name: sample
on:
  push:
    tags: [ '**' ]
env:
  MAJORVERSION: ''
  MINORVERSION: ''
  FULLVERSION: ''
  COMPONENT_NAME: 'sample'   # set this to the web component name you are using
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - name: 'Get Version'
      id: get_version
      uses: dhkatz/get-version-action@v3.0.0
    - name: 'Check for correct naming convention'
      if: ${{ !steps.get_version.outputs.is-semver }}
      run: exit 1
    - name: 'Get major version from tag'
      run: echo "MAJORVERSION=${GITHUB_BRANCH}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ steps.get_version.outputs.major }}
    - name: 'Get minor version from tag'
      run: echo "MINORVERSION=${GITHUB_BRANCH}.${GITHUB_BRANCH_MINOR}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ steps.get_version.outputs.major }}
        GITHUB_BRANCH_MINOR: ${{ steps.get_version.outputs.minor }}
    - name: Get patch (full) version from tag
      run: echo "FULLVERSION=${GITHUB_BRANCH}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ steps.get_version.outputs.version-without-v }}
    - name: Display major version install
      run: echo "Installing major version ${MAJORVERSION}"
    - name: Display minor version install
      run: echo "Installing minor version ${MINORVERSION}"
    - name: Display patch (full) version install
      run: echo "Installing patch (full) version ${FULLVERSION}"

